In [8]:
import numpy as np
# importando bibliote a ser usada 
# as significa como nesse caso as np seria com np ou apelidado de np, pra ficar menor.
# agora fazendo um pouco de array
aray=np.array([1,2,3,4])
print(aray)

[1 2 3 4]


In [53]:
# dica: se no seu deu errado é porque a quantidade de objetos na 1º tupla não é o mesmo na 2º
aray = np.array([(2,4,5),(12,23,2)]) # array com mais de uma linha, matriz.
aray

array([[ 2,  4,  5],
       [12, 23,  2]])

In [61]:
ara = np.zeros((3,2)) # a = 
ara

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# explicando um pouco o porquê de fazer isso pode ser errado
aray1 = aray
print(aray1)

[1 2 3 4]


In [14]:
# por mais que pareça que atribuir uma variavel dentro de outra e não seu valor seja mais facil
# isso pode te dar problemas.
aray1[0]=0
print(aray,aray1) # como este
# isso ocorre pois é como se você estivesse criando um atalho, ou seja, qualquer alteração feita em um
# ocorrerá no outro.

[0 2 3 4] [0 2 3 4]


In [22]:
# todas as alterações feitas em um vão ser aplicadas no outro por ocuparem o mesmo lugar e serem o mesmo 
# objeto com a unica diferença de terem nomes diferentes
# logo o que você fará é usar a biblioteca copy
import copy

aray=np.array([1,2,3,4])
aray1 = aray
print("sem usar copy:")
print("Aray=",aray," Aray1=",aray1)

print("\nusando copy:")
aray1 = copy.deepcopy(aray)
aray1[0]=11
print("Aray =",aray," Aray1 =",aray1)

sem usar copy:
Aray= [1 2 3 4]  Aray1= [1 2 3 4]

usando copy:
Aray= [1 2 3 4]  Aray1= [11  2  3  4]


In [30]:
aray2 = np.array([(1),("limão"),("com marcuja"),(1)]) 
print(aray2) # todos os elementos do array tem que ser do mesmo tipo, ou seja, se tiver str e int, str sera 
# predominante. 

['1' 'limão' 'com marcuja' '1']


In [49]:
aray2 = np.array([("limão"),("com marcuja"),(1,2)]) # e se tiver mais de um numero, retornar uma mensagem
print(aray2) # que pode ser considerado um alerta de error, pois, há apenas uma sting logo ter 2 int seria 
# errado.

['limão' 'com marcuja' (1, 2)]


<ipython-input-49-ce38ba586168>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  aray2 = np.array([("limão"),("com marcuja"),(1,2)]) # e se tiver mais de um numero, retornar uma mensagem


In [50]:
# esse erro tambem dá com um array de numeros
la = np.array([(1),(1),(1,2)])
la

<ipython-input-50-b648e93a1862>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  la = np.array([(1),(1),(1,2)])


array([1, 1, (1, 2)], dtype=object)